#glory_content_show:
#    path: /content/{id}
#    defaults: { _controller: GloryContentBundle:Default:show }

glory_admin_content:
    resource: |
        alias: glory.content
        section: admin
        templates: SyliusAdminBundle:Crud
        grid: glory_content
    type: sylius.resource
    prefix: /admin

