services:
    glory_content.content_manager:
        class: Glory\Bundle\ContentBundle\Model\ContentManager
        arguments: [ @service_container ]
    glory_content.form.content_form:
        class: Glory\Bundle\ContentBundle\Form\Type\ContentFormType
        tags: 
            - { name:form.type, alias:glory_content_form }
