services:
    glory.content.form.type:
        class: Glory\Bundle\ContentBundle\Form\Type\ContentType
        tags:
            - { name: form.type }
        arguments: ['%glory.model.content.class%']

